cache:
  paths:
    - .composer/cache

variables:
  TRAVIS_BUILD_DIR: "$CI_PROJECT_DIR"
  MUSTACHE_IGNORE_NAMES: "email_html_body.mustache, email_html.mustache, email_text.mustache"
  COMPOSER_HOME: "$CI_PROJECT_DIR/.composer/cache"
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  POSTGRES_USER: "postgres"
  POSTGRES_HOST_AUTH_METHOD: "trust"
  MYSQL_USER: "root"
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"

services:
  - postgres:11
  - name: mysql:8.0.23
    command: ["mysqld", "--port=6033", "--default-authentication-plugin=mysql_native_password"]
  - mariadb:10.4-bionic
  - docker:dind

test:
  image: amcdev/moodle-plugin-ci:7.4-n.16
  variables:
    MOODLE_BRANCH: "MOODLE_400_STABLE"
  before_script:
    - cd ../..
    - echo $DB_HOST $DB_PORT
    - moodle-plugin-ci install --moodle="moodle-upstream-core" --db-host=$DB_HOST --db-port=$DB_PORT
  script:
    - moodle-plugin-ci phplint
    - moodle-plugin-ci phpcpd
    - moodle-plugin-ci phpmd
    - moodle-plugin-ci codechecker
    - moodle-plugin-ci validate
    - moodle-plugin-ci savepoints
    - moodle-plugin-ci mustache
#    - moodle-plugin-ci grunt
    - moodle-plugin-ci phpdoc
    - moodle-plugin-ci phpunit
    - moodle-plugin-ci behat
  parallel:
    matrix:
      - DB: pgsql
        DB_HOST: postgres

      - DB: mysqli
        DB_HOST: mysql
        DB_PORT: 6033

      - DB: mariadb
        DB_HOST: mariadb